
package com.ws.temperature;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "TempWsService", targetNamespace = "http://temperature.ws.com", wsdlLocation = "file:/C:/JavaApplications/eclipse_ganymede/TempWs/wsdl/converterTemp.wsdl")
public class TempWsService
    extends Service
{

    private final static URL TEMPWSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/JavaApplications/eclipse_ganymede/TempWs/wsdl/converterTemp.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TEMPWSSERVICE_WSDL_LOCATION = url;
    }

    public TempWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempWsService() {
        super(TEMPWSSERVICE_WSDL_LOCATION, new QName("http://temperature.ws.com", "TempWsService"));
    }

    /**
     * 
     * @return
     *     returns TempWs
     */
    @WebEndpoint(name = "converterTempSOAP")
    public TempWs getConverterTempSOAP() {
        return (TempWs)super.getPort(new QName("http://temperature.ws.com", "converterTempSOAP"), TempWs.class);
    }

}
