package mappings_re;

// Generated Jan 31, 2009 10:07:52 PM by Hibernate Tools 3.2.2.GA

/**
 * Child generated by hbm2java
 */
public class Child implements java.io.Serializable {

	private int id;
	private Parent parent;
	private String childName;
	private String childSurname;
	private int childAge;

	public Child() {
	}

	public Child(int id, Parent parent, String childName, String childSurname,
			int childAge) {
		this.id = id;
		this.parent = parent;
		this.childName = childName;
		this.childSurname = childSurname;
		this.childAge = childAge;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	public String getChildSurname() {
		return this.childSurname;
	}

	public void setChildSurname(String childSurname) {
		this.childSurname = childSurname;
	}

	public int getChildAge() {
		return this.childAge;
	}

	public void setChildAge(int childAge) {
		this.childAge = childAge;
	}

}
