package mappings_re;

// Generated Jan 31, 2009 10:07:52 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Parent generated by hbm2java
 */
public class Parent implements java.io.Serializable {

	private int id;
	private String parentName;
	private String parentSurname;
	private Set<Child> childs = new HashSet<Child>(0);

	public Parent() {
	}

	public Parent(int id, String parentName, String parentSurname) {
		this.id = id;
		this.parentName = parentName;
		this.parentSurname = parentSurname;
	}

	public Parent(int id, String parentName, String parentSurname,
			Set<Child> childs) {
		this.id = id;
		this.parentName = parentName;
		this.parentSurname = parentSurname;
		this.childs = childs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getParentSurname() {
		return this.parentSurname;
	}

	public void setParentSurname(String parentSurname) {
		this.parentSurname = parentSurname;
	}

	public Set<Child> getChilds() {
		return this.childs;
	}

	public void setChilds(Set<Child> childs) {
		this.childs = childs;
	}

}
