package org.domain.generateSeam.entity;

// Generated Jan 28, 2009 12:18:03 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Details generated by hbm2java
 */
@Entity
@Table(name = "details", schema = "public")
public class Details implements java.io.Serializable {

	private int id;
	private Testentity testentity;
	private String email;
	private String pass;
	private String zip;

	public Details() {
	}

	public Details(int id, Testentity testentity) {
		this.id = id;
		this.testentity = testentity;
	}

	public Details(int id, Testentity testentity, String email, String pass,
			String zip) {
		this.id = id;
		this.testentity = testentity;
		this.email = email;
		this.pass = pass;
		this.zip = zip;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fid", nullable = false)
	@NotNull
	public Testentity getTestentity() {
		return this.testentity;
	}

	public void setTestentity(Testentity testentity) {
		this.testentity = testentity;
	}

	@Column(name = "email", length = 25)
	@Length(max = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "pass", length = 25)
	@Length(max = 25)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "zip", length = 25)
	@Length(max = 25)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

}
