package org.domain.generateSeam.entity;

// Generated Jan 28, 2009 12:18:03 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Testentity generated by hbm2java
 */
@Entity
@Table(name = "testentity", schema = "public")
public class Testentity implements java.io.Serializable {

	private long id;
	private Integer version;
	private String name;
	private Set<Details> detailses = new HashSet<Details>(0);

	public Testentity() {
	}

	public Testentity(long id) {
		this.id = id;
	}

	public Testentity(long id, String name, Set<Details> detailses) {
		this.id = id;
		this.name = name;
		this.detailses = detailses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "name", length = 20)
	@Length(max = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "testentity")
	public Set<Details> getDetailses() {
		return this.detailses;
	}

	public void setDetailses(Set<Details> detailses) {
		this.detailses = detailses;
	}

}
